name: geoanomaly
description: Location-based AR game for discovering hidden zones and collecting artifacts
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ UI & Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  cached_network_image: ^3.3.1

  # ✅ State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # ✅ Navigation
  go_router: ^14.2.0

  # ✅ Maps & Location (OPRAVENÉ verzie)
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

  # ✅ HTTP & API
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1

  # ✅ Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  # ✅ Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # ✅ Code Generation
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/